//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Query {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Query() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Data.Query", typeof(Query).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DELETE_NUDO.
        /// </summary>
        internal static string Delete_Nudo {
            get {
                return ResourceManager.GetString("Delete_Nudo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DELETE_NUDO_STATE.
        /// </summary>
        internal static string Delete_Nudo_State {
            get {
                return ResourceManager.GetString("Delete_Nudo_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a READ_ALL_CAMPO.
        /// </summary>
        internal static string Read_all_Campo {
            get {
                return ResourceManager.GetString("Read_all_Campo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a READ_ALL_LOTE.
        /// </summary>
        internal static string Read_all_Lote {
            get {
                return ResourceManager.GetString("Read_all_Lote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a READ_ALL_NUDO.
        /// </summary>
        internal static string Read_all_Nudo {
            get {
                return ResourceManager.GetString("Read_all_Nudo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a READ_ALL_NUDO_STATE.
        /// </summary>
        internal static string Read_All_Nudo_State {
            get {
                return ResourceManager.GetString("Read_All_Nudo_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a READ_ALL_PLANTA.
        /// </summary>
        internal static string Read_all_Planta {
            get {
                return ResourceManager.GetString("Read_all_Planta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a READ_STATE.
        /// </summary>
        internal static string Read_State {
            get {
                return ResourceManager.GetString("Read_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SAVE_NUDO_STATE.
        /// </summary>
        internal static string Save_Estado {
            get {
                return ResourceManager.GetString("Save_Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SAVE_EVENT_NUDO_STATE.
        /// </summary>
        internal static string Save_Event_Nudo_State {
            get {
                return ResourceManager.GetString("Save_Event_Nudo_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SAVE_LOTE.
        /// </summary>
        internal static string Save_Lote {
            get {
                return ResourceManager.GetString("Save_Lote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SAVE_NUDO.
        /// </summary>
        internal static string Save_Nudo {
            get {
                return ResourceManager.GetString("Save_Nudo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SAVE_NUDO_2.
        /// </summary>
        internal static string Save_Nudo2 {
            get {
                return ResourceManager.GetString("Save_Nudo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SAVE_PLANTA.
        /// </summary>
        internal static string Save_Planta {
            get {
                return ResourceManager.GetString("Save_Planta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a READ_ULTIMO_NUDO.
        /// </summary>
        internal static string Ultimo_Nudo {
            get {
                return ResourceManager.GetString("Ultimo_Nudo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UPDATE_NUDO.
        /// </summary>
        internal static string Update_Nudo {
            get {
                return ResourceManager.GetString("Update_Nudo", resourceCulture);
            }
        }
    }
}
